### ISSUE TITLE
The specified object store was not found

### ISSUE THREAD

**Issue by Joeao** [y-js/y-indexeddb#1]
Hello there,

Tried using the IndexDB adaptor after using y-memory for some time and this error occurred.
```javascript
Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.

Store @ y-indexeddb.es6:9
SmallLookupBuffer @ y.js:2899
Transaction @ y-indexeddb.es6:98
handleTransactions @ y-indexeddb.es6:250
request.onsuccess @ y-indexeddb.es6:279
```

It is initiated as follows:
```javascript
Y({
	db: {
		name: 'indexeddb'
	},
	connector: {
		name: 'websockets-client',
		room: 'y-' + ID,
		socket: io,
		type: 'n'
	},
	sourceDir: '/javascripts/Plugins/yjs',
	share: {
		richtext: 'Richtext',
		map: 'Map'
	}
}).then(function (y) {
	doStuff()
});
```
I checked the repo to see if I should be doing something in preparation but couldn't see anything. Let me know if you require more information.

Chrome 50.0
OSX 10.11.3

**Comment by DadaMonad** [comment]
Thanks, well reported.

I'm not able to reproduce this problem. It could be possible that this is somehow tied to having a shared socked connection. Maybe it helps to specify namespace in db like this: 
```
Y({
    db: {
        name: 'indexeddb',
        namespace: 'myIndexeddbDatabase'
    },
    connector: {
        name: 'websockets-client',
        room: 'y-' + ID,
        socket: io,
        type: 'n'
    },
    sourceDir: '/javascripts/Plugins/yjs',
    share: {
        richtext: 'Richtext',
        map: 'Map'
    }
})
```

If that doesn't help, can you please share your bower.json / package.json?

**Comment by Joeao** [comment]
My B. I was running 11.0.3, upgrading to 11.0.4 and/or 11.1.0 fixed it.
