### ISSUE TITLE
array insert happens twice on receiving end

### ISSUE THREAD

**Issue by lukebarlow** [y-js/y-indexeddb#2]
Steps to reproduce : Set up a Y object in two browsers, using the following configuration, and open the page twice, with two windows of the _same_ browser.

```
Y({
  db: {
    name: 'indexeddb'
  },
  connector: {
    name: 'websockets-client',
    room: 'test'
  },
  share: {
    state : 'Map'
  }
}).then((y) => { window.y = y })
```

In window A, type `var a = y.set('list', Y.Array);a.push([1])`

Now, in window B, inspect the result with `console.log(y.get('list').toArray()`. The result is `[ 1, 1 ]`, rather than the expected `[1]`. This doesn't occur when the receiving window is in a separate browser, or when the two parts of setting the list `var a = y.set('list', Y.Array)` and populating it `a.push([1])` are executed with a pause inbetween.

**Comment by DadaMonad** [comment]
Fixed in y-indexeddb@v8.1.4

**Comment by lukebarlow** [comment]
I'm still seeing the issue

**Comment by DadaMonad** [comment]
Your are right. I only fixed it for chrome. It's still not working in Firefox

**Comment by DadaMonad** [comment]
I found a better solution now. You have to update to update y-array@10.0.4 and y-map@10.0.3 (same issue could happen in y-map)

**Comment by lukebarlow** [comment]
Brilliant. Yes, works now
