### ISSUE TITLE
Syncing problems

### ISSUE THREAD

**Issue by dennislaupman** [y-js/y-indexeddb#5]
Hello, 

We've got some problems with resyncing the local indexDB storage with the server. When we turn off the network connection and after a few seconds reconnect,  the client shows the local offline generated text, but don't (re)sync the data to the other clients.

Also after CMD + SHIFT + R the data shows in the reconnected client, so that part works well. 

See our prototype files too see whats happening.

Thanks Dennis

[y-test.zip](https://github.com/y-js/y-indexeddb/files/1522150/y-test.zip)

**Comment by dmonad** [comment]
Hi Dennis,
I'm sorry to say that. But I don't have the time to fix this issue in the 12.x.x branch.
I will update y-indexeddb to work with Yjs version 13 (still in beta).
