### ISSUE TITLE
Can we use IPFS Connector?

### ISSUE THREAD

**Issue by harrshasri** [y-js/y-indexeddb#6]
Can we use IPFS Connector?

**Comment by dmonad** [comment]
Please reopen a new issue with more details to your question. What does this have to do with y-indexeddb?

**Comment by dmonad** [comment]
The connector interface is completely decoupled from the database adapter. So yes, you can use y-ipfs + y-indexeddb. This is by the way how peerpad works.

**Comment by harrshasri** [comment]
Thanks @dmonad

**Comment by dmonad** [comment]
Welcome!
